export enum ErrorCode {
  VALIDATION = 'VALIDATION',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  BAD_REQUEST = 'BAD_REQUEST',
  CONFLICT = 'CONFLICT',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
}
